version: 2

project_name: vars

builds:
    - main: .
      binary: vars
      ldflags:
          - -s -w -X github.com/vars-cli/vars/cmd.Version={{.Version}}
      goos:
          - linux
          - darwin
      goarch:
          - amd64
          - arm64

archives:
    - formats: [tar.gz]
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
    name_template: checksums.txt

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^ci:"
            - "^chore:"
